[package]
name = "simple-http-server"
version = "0.4.2"
authors = ["thewawar <thewawar@gmail.com>"]
license = "MIT"
description = "SimpleHTTPServer.py"
keywords = ["simple", "http", "server", "static"]
repository = "https://github.com/TheWaWaR/simple-http-server"

[dependencies]
clap = "2.24.2"
termcolor = "0.3.2"
lazy_static = "0.2.8"
time = "0.1.37"
chrono = "0.4.0"
flate2 = "0.2.19"
filetime = "0.1.10"
pretty-bytes = "0.2.1"
url = "^1.4.0"
hyper-native-tls = "0.2.2"
conduit-mime-types = "0.7.3"
# Iron crates
iron = "^0.5.0"
multipart = { version="0.12.0", features=["iron"] }
